"""
cut_sample.py — Copy pre-cut stage audio to whisper-sandbox

Stage audio (m4a) is pre-generated by gen_stage_gt.py and stored in GroundTrue/.
This script copies only the m4a to whisper-sandbox/ so Whisper experiments can
be run directly.

GT SRT (turboscribe) stays in GroundTrue/ — verify_cer.py finds it there
automatically without needing a copy in the sandbox.

Usage:
    python cut_sample.py 2357_2025_q4               # all stages
    python cut_sample.py 2357_2025_q4 --stage 0     # stage0 only
    python cut_sample.py 2357_2025_q4 --stage 1     # stage1 only
    python cut_sample.py 2357_2025_q4 --stage 2     # stage2 only

Output (copies to whisper-sandbox/):
    whisper-sandbox/2357_2025_q4_stage0.m4a
    whisper-sandbox/2357_2025_q4_stage1.m4a
    whisper-sandbox/2357_2025_q4_stage2.m4a
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

SCRIPT_DIR      = Path(__file__).parent
GT_DIR          = SCRIPT_DIR / "GroundTrue"
DEFAULT_SANDBOX = SCRIPT_DIR / "whisper-sandbox"


def copy_stage(stem: str, stage: int, sandbox: Path) -> None:
    suffix = f"stage{stage}"
    sandbox.mkdir(parents=True, exist_ok=True)

    # Audio m4a — copy to sandbox for Whisper experiments
    src_m4a = GT_DIR / f"{stem}_{suffix}.m4a"
    dst_m4a = sandbox / f"{stem}_{suffix}.m4a"
    if not src_m4a.exists():
        print(f"  ERROR: {src_m4a} not found — run gen_stage_gt.py {stem} first")
        return
    shutil.copy2(src_m4a, dst_m4a)
    print(f"  Copied {src_m4a.name} -> whisper-sandbox/  ({src_m4a.stat().st_size // 1024 // 1024} MB)")

    # GT SRT stays in GroundTrue/ — verify_cer.py finds it there automatically
    srt_path = GT_DIR / f"{stem}_{suffix}_turboscribe.srt"
    if srt_path.exists():
        lines = len(srt_path.read_text(encoding='utf-8').splitlines())
        print(f"  GT SRT  {srt_path.name}  ({lines} lines) — in GroundTrue/, no copy needed")
    else:
        print(f"  [GT] {stem}_{suffix}_turboscribe.srt not found in GroundTrue/")


def main():
    parser = argparse.ArgumentParser(description="Copy pre-cut stage audio to whisper-sandbox")
    parser.add_argument("stem", help="e.g. 2357_2025_q4")
    parser.add_argument("--stage", type=int, default=None, choices=[0, 1, 2],
                        help="Stage to copy (default: all stages)")
    parser.add_argument("--out-dir", default=str(DEFAULT_SANDBOX))
    args = parser.parse_args()

    sandbox = Path(args.out_dir)
    stages  = [args.stage] if args.stage is not None else [0, 1, 2]

    print(f"\nCopy Stage Audio — {args.stem}")
    for s in stages:
        print(f"  [stage{s}]")
        copy_stage(args.stem, s, sandbox)

    print(f"\nNext — run Whisper experiments on each stage audio, then verify:")
    stage_stems = " ".join(f"{args.stem}_stage{s}" for s in stages)
    print(f"  python verify_cer.py {stage_stems}")


if __name__ == "__main__":
    main()
